security:
  oauth2:
    client:
      client-id: client
      client-secret: pass
      
spring:
  datasource:
    url: jdbc:mysql://localhost/authorization_server
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
